# Week One Task

### Q: Write a NumPy program to create an array of all even integers from 30 to 70.

In [1]:
import numpy as np
even_integers = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_integers)

Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


We will import Numpy library as np.<br>
Than declare a varibale as even_integer.<br>
Call the function np.arrange make a list of all the integers from 30 to 71 i.e 70.<br>
Than print our list of even numbers.<br>

### Q: Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.
#### A: Here's a NumPy code snippet that generates an array of 15 random numbers from a standard normal distribution using the `numpy.random.normal` function:


In [3]:
import numpy as np
random_numbers = np.random.normal(size=15)
print("Array of 15 random numbers from a standard normal distribution:", random_numbers)


Array of 15 random numbers from a standard normal distribution: [ 0.82610878 -0.19818386  1.86696648  1.06158977  1.36769018 -1.68827023
  0.45812366  0.83658743  1.51849281 -1.08658318  0.16623446 -0.87700485
  1.81017497 -1.12155942 -0.57233441]


In the above example,<br> np.random.normal(size=15) generates an array of 15 random numbers following a standard normal distribution (mean=0, standard deviation=1).







### Q:How to compute the cross-product of two matrices in NumPy?

In [4]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

cross_product = np.cross(matrix1, matrix2)

print("Cross-product of the two matrices:")
print(cross_product)


Cross-product of the two matrices:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In this example,<br> np.cross(matrix1, matrix2) calculates the cross-product of matrix1 and matrix2.<br> The resulting matrix is printed, showing the cross-product values.

### Q: How to compute the determinant of an array using NumPy?

In [5]:
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])

determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)


Determinant of the matrix: 10.000000000000002


In this example,<br> np.linalg.det(matrix) computes the determinant of the square matrix.<br> Note that the matrix must be square (having the same number of rows and columns) for the determinant to be defined.

### Q: How to create a 3x3x3 array with random values using NumPy?

In [6]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print("3x3x3 Array with random values:")
print(random_array)


3x3x3 Array with random values:
[[[0.75688738 0.55973031 0.49420521]
  [0.04974709 0.64190306 0.51238306]
  [0.72209162 0.10888168 0.47549515]]

 [[0.01946996 0.36003871 0.28449575]
  [0.57459068 0.7695341  0.98300365]
  [0.81535599 0.40533881 0.42203142]]

 [[0.37134444 0.29447102 0.60406838]
  [0.75219796 0.77194608 0.15519072]
  [0.47357851 0.68578955 0.26547866]]]


In this example<br> np.random.rand(3, 3, 3) generates a 3x3x3 array filled with random values between 0 (inclusive) and 1 (exclusive)

### Q: How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?

In [7]:
import numpy as np
random_array = np.random.rand(5, 5)
print("5x5 Array with random values:")
print(random_array)

minimum_value = np.min(random_array)
maximum_value = np.max(random_array)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)


5x5 Array with random values:
[[0.10151892 0.90066669 0.70907943 0.05571676 0.66151189]
 [0.8180824  0.30450039 0.97431527 0.90122744 0.17695773]
 [0.27197575 0.90823941 0.62087317 0.59533918 0.15454298]
 [0.81270428 0.5311883  0.11049869 0.64699527 0.52068865]
 [0.69891368 0.32877184 0.41143687 0.46062318 0.26668167]]
Minimum value: 0.055716756017669455
Maximum value: 0.9743152749669002


In this example,<br> np.random.rand(5, 5) generates a 5x5 array filled with random values between 0 (inclusive) and 1 (exclusive). The np.min and np.max functions are then used to find the minimum and maximum values in the array, respectively. The results are printed for reference.

### Q: How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [9]:
import numpy as np

sample_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

mean_values = np.mean(sample_array, axis=1)

std_deviation_values = np.std(sample_array, axis=1)

variance_values = np.var(sample_array, axis=1)

print("Mean along the second axis:", mean_values)
print("Standard deviation along the second axis:", std_deviation_values)
print("Variance along the second axis:", variance_values)


Mean along the second axis: [2. 5. 8.]
Standard deviation along the second axis: [0.81649658 0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667 0.66666667]


In this example,<br> axis=1 specifies that the calculations should be performed along the second axis (columns). 